---
# handlers file for gse_build_source
- name: dnf_update
  dnf:
    name: "*"
    state: latest
    update_cache: yes
  become: yes

- name: Restart PGSQL
  systemd:
    name: postgresql
    state: restarted
  become: yes

  
